---
sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - '5.20'
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
    - TRAVIS_PERL_DEBUG=1
cache:
  directories:
    - $HOME/perl5
before_install:
  - git clone git://github.com/autarch/helpers --branch autarch/cache-mode ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --travis-cache --deps       # installs prereqs, including recommends
before_script:
  - coverage-setup
script:
  - prove -l -j$(test-jobs) $(test-files)   # parallel testing
